apiVersion: apps/v1
kind: Deployment
metadata:
  name: sjjeon-nginx
spec:
  selector:
    matchLabels:
      run: sjjeon-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: sjjeon-nginx
    spec:
      containers:
<<<<<<< HEAD:base/deployment.yaml
      - name: sjjeon-nginx
        image: nginx
=======
      - name: my-app
        image: 10.0.1.150:5000/sjjeon/argocd-deploy:123
>>>>>>> f8a4a9c5138ede837cbc963443d3677577f53041:deployment.yaml
        ports:
        - containerPort: 80
