patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
commonLabels:
  env: dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: 10.0.1.150:5000/sjjeon/argocd-deploy
  newTag: "130"
